/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableTableIdRouteImport } from './routes/table.$tableId'
import { Route as RestaurantSlugRouteImport } from './routes/restaurant.$slug'
import { Route as ChefChefIdRouteImport } from './routes/chef.$chefId'
import { Route as AuthenticatedOpsRouteImport } from './routes/_authenticated/ops'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableTableIdRoute = TableTableIdRouteImport.update({
  id: '/table/$tableId',
  path: '/table/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSlugRoute = RestaurantSlugRouteImport.update({
  id: '/restaurant/$slug',
  path: '/restaurant/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ChefChefIdRoute = ChefChefIdRouteImport.update({
  id: '/chef/$chefId',
  path: '/chef/$chefId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOpsRoute = AuthenticatedOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me': typeof AuthenticatedMeRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/chef/$chefId': typeof ChefChefIdRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/table/$tableId': typeof TableTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/me': typeof AuthenticatedMeRoute
  '/ops': typeof AuthenticatedOpsRoute
  '/chef/$chefId': typeof ChefChefIdRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/table/$tableId': typeof TableTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/ops': typeof AuthenticatedOpsRoute
  '/chef/$chefId': typeof ChefChefIdRoute
  '/restaurant/$slug': typeof RestaurantSlugRoute
  '/table/$tableId': typeof TableTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/me'
    | '/ops'
    | '/chef/$chefId'
    | '/restaurant/$slug'
    | '/table/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/me'
    | '/ops'
    | '/chef/$chefId'
    | '/restaurant/$slug'
    | '/table/$tableId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/me'
    | '/_authenticated/ops'
    | '/chef/$chefId'
    | '/restaurant/$slug'
    | '/table/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChefChefIdRoute: typeof ChefChefIdRoute
  RestaurantSlugRoute: typeof RestaurantSlugRoute
  TableTableIdRoute: typeof TableTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/$tableId': {
      id: '/table/$tableId'
      path: '/table/$tableId'
      fullPath: '/table/$tableId'
      preLoaderRoute: typeof TableTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$slug': {
      id: '/restaurant/$slug'
      path: '/restaurant/$slug'
      fullPath: '/restaurant/$slug'
      preLoaderRoute: typeof RestaurantSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chef/$chefId': {
      id: '/chef/$chefId'
      path: '/chef/$chefId'
      fullPath: '/chef/$chefId'
      preLoaderRoute: typeof ChefChefIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ops': {
      id: '/_authenticated/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof AuthenticatedOpsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedOpsRoute: typeof AuthenticatedOpsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedOpsRoute: AuthenticatedOpsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ChefChefIdRoute: ChefChefIdRoute,
  RestaurantSlugRoute: RestaurantSlugRoute,
  TableTableIdRoute: TableTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
